spring:
  datasource:
    url: jdbc:h2:mem:midasdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    jmx:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update    # Auto-create/update schema for UserRecord & TransactionRecord
    show-sql: true         # Show SQL queries in console for debugging
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true        # Enable H2 web console
      path: /h2-console    # Accessible at http://localhost:8080/h2-console

  kafka:
    bootstrap-servers: localhost:9092   # For local Kafka (Testcontainers will override in tests)
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer.properties:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

